import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import SessionProvider from "../components/providers/SessionProvider";
import QueryProvider from "@/components/providers/QueryProvider";
import MobileBottomNav from "@/components/MobileBottomNav";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Techno Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Navbar></Navbar>
        {/* <div className="min-h-full flex flex-col">{children}</div> */}
        <QueryProvider>
          <SessionProvider>{children}</SessionProvider>
          <MobileBottomNav />
        </QueryProvider>
        <Footer></Footer>
</body>
    </html>
  );
}
